In [38]:

import cv2
import numpy as np
import os



In [21]:
img = cv2.imread('image.jpg')
img=cv2.resize(img,(500,600)) # resize image
cv2.imshow('image',img)      # image frame
cv2.waitKey(0)
cv2.destroyAllWindows()     


In [17]:
v=np.array([1,2,3,1,2,3])
np.hstack((v,v))

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [18]:
v=np.array([1,2,3,1,2,3])
np.vstack((v,v))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [9]:
img

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[ 84,  84,  84],
        [225, 225, 225],
        [254, 254, 254],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[ 50,  50,  50],
        [212, 212, 212],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[ 41,  41,  41],
        [208, 208, 208],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [ ]:
# images combined in horizontally
img1=cv2.imread('image2.png')
img1=cv2.resize(img1,(500,600))
h=np.hstack((img1,img1))
cv2.imshow('Hrizontal join',h)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# image combined in vertically
img1=cv2.imread('image2.png')
img1=cv2.resize(img1,(500,600))
vertical_stack=np.vstack((img,img1))
cv2.imshow('vertical',vertical_stack)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# image combined both horizontal and vertical
img=cv2.imread('image.jpg')
img=cv2.resize(img,(300,300))
h=np.hstack((img,img,img))
v=np.vstack((h,h))
cv2.imshow('Frame of 4 ',v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [44]:
# slideshow
list_name=os.listdir(r'C:\Users\asus\OneDrive\Desktop\Photos')
list_name

['image1.jpg', 'image2.jpg', 'image3.jpg', 'image4.jpg', 'image5.jpg']

In [ ]:
for name in list_name:
    path='C:\\Users\\asus\\OneDrive\\Desktop\\Photos'
    img_name=path+"\\"+name
    print(img_name)
    img=cv2.imread(img_name)
    img=cv2.resize(img,(500,600))
    cv2.imshow('windowname',img)
    # cv2.waitKey(2000)
    cv2.waitKey(0) # control by keyboard
    cv2.destroyAllWindows()


C:\Users\asus\OneDrive\Desktop\Photos\image1.jpg
C:\Users\asus\OneDrive\Desktop\Photos\image2.jpg
C:\Users\asus\OneDrive\Desktop\Photos\image3.jpg
C:\Users\asus\OneDrive\Desktop\Photos\image4.jpg
C:\Users\asus\OneDrive\Desktop\Photos\image5.jpg
